### ISSUE TITLE
removal function

### ISSUE THREAD

**Issue by nityanantan23** [the-deepnet/Data-Grabber#1]
how to remove the program from the victim device completely?

**Comment by muneebwanee** [comment]
Add these into the command when creating the exe if you want
| PyInstaller Options |
| ------------------------------------ |
| `-n name` The name of the compiled EXE (Defaults to the name of the original Python file) |
| `-i icon.ico` The icon. You can specify a directory to an icon file, or do NONE for a default EXE icon. |
| `--clean` Removes all temporary files so you only have what you need. |
| `--uac-admin` Modified the MANIFEST so that it will request UAC permissions upon running. |
| `--hidden-import MODULENAME` Adds a module without it being present in the script. |
